Implement "on_no_change" for files
RexOps/Rex pull request #1386
Opened 2020-07-26 20:56 UTC by choroba

This PR fixes #670 by implementing the proposed feature. I changed the name to "on_no_change" as it sounds much better than "on_unchanged", but English is my second language, so my feeling might be wrong.

## Checklist

- [x] based on top of latest source code 
- [x] changelog entry included 
- [ ] tests pass on Travis CI 
- [ ] git history is clean    
- [ ] git commit messages are [well-written](https://chris.beams.io/posts/git-commit/#seven-rules)

2020-07-26 20:57 UTC, choroba commented
Greetings from the PullRequest.Club.

2020-08-02 17:39 UTC, ferki commented
Thanks for your contribution and participation in Pull Request Club, @choroba! ;)

Yes, I think `on_no_change` fits better the existing interface than `not_changed` or `on_unchanged`, as it is closer to its `on_change` pair.

I expected the first implementation would only consider the `file` command. Thanks for going the extra mile and adding this option to other related commands as well, even though it inflated the scope. I'll give it a full review at a later time.

2020-09-30 17:23 UTC, ferki commented
I'm rebasing this PR on top of current default branch due to the current merge conflicts. I'm also curious how the code coverage changes with this. We might need to add further tests accordingly.

2020-09-30 19:06 UTC, ferki requested changes
Thanks again @choroba for your contribution!

As I commented earlier, I already rebased it on top of current default branch. I had to add an autogenerated perltidy-only commit but I didn't have to change anything else.

Based on my full reading of the changes, there's only slight changes required:
- add some more docs about the on_no_change hook
- fix one debug message

I plan to take care of that soon, so it could be already included in the next release. I might or might not squash together some of the commits once this is finished, but I'll try to make sure not to change the original commits if possible.

2020-09-30 19:06 UTC, ferki commented on lib/Rex/Commands/File.pm
> +  my ( $option, $on_change, $on_no_change );
Let's mention the on_no_change option in the docs of this function too.

2020-09-30 20:25 UTC, ferki commented on lib/Rex/Commands/File.pm
> +    ( $option->{on_no_change} || sub { } )->($file);
I moved it in a follow up.

2020-09-30 20:25 UTC, ferki commented on lib/Rex/Commands/File.pm
> +        "File $file has been changed (md5 $new_md5)... Running on_no_change");
Fixed.

2020-09-30 20:27 UTC, ferki commented on lib/Rex/Commands/File.pm
> +  my ( $option, $on_change, $on_no_change );
I've included a few more mentions.

2020-09-30 20:28 UTC, ferki approved these changes

2020-09-30 20:43 UTC, ferki commented
Oh, last minute notice: this does not completely fix #670 yet, as there are a few more resources which have `on_change` hooks, but it's a great start, and probably one of the most important one anyway. So after merging, I probably will need to reopen the issue, and make further notes there.

2020-09-30 20:43 UTC, merged

2020-09-30 21:10 UTC, choroba commented
Thanks for solving all the review comments before I had time to even look at them :-)